ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER QLKS IDENTIFIED BY QLKS1234;
GRANT ALL PRIVILEGES TO QLKS;
GRANT CREATE SESSION TO QLKS;

CREATE TABLE QLKS.NHANVIEN (
    MANV INT,
    TENNV NVARCHAR2(35),
    DIACHI NVARCHAR2(100),
    SDT VARCHAR(10),
    CHUCVU NVARCHAR2(20),
    PRIMARY KEY (MANV)
);

CREATE TABLE QLKS.KHACHHANG (
    MAKH INT,
    TENKH NVARCHAR2(35),
    SDT VARCHAR(10),
    DIACHI NVARCHAR2(100),
    EMAIL VARCHAR(50),
    SOFAX VARCHAR(11),
    TENDOAN NVARCHAR2(35),
    SOLUONGNGUOI INT,
    PRIMARY KEY (MAKH)
);

CREATE TABLE QLKS.LOAIPHONG (
    TENLOAIPHONG NVARCHAR2(50),
    SOLUONG INT,
    SOPHONGTRONG INT,
    GIA INT,
    MOTA NVARCHAR2(200),
    PRIMARY KEY (TENLOAIPHONG)
);

CREATE TABLE QLKS.PHONG (
    MAPHONG NVARCHAR2(10),
    TENLOAIPHONG NVARCHAR2(50),
    TINHTRANG NVARCHAR2(20),
    TTDONDEP NVARCHAR2(20),
    PRIMARY KEY (MAPHONG)
);

CREATE TABLE QLKS.DATPHONG (
    MADATPHG INT,
    MAKH INT,
    TENLOAIPHONG NVARCHAR2(50),
    NGAYDEN DATE,
    SODEMLUUTRU INT,
    PRIMARY KEY (MADATPHG)
);

CREATE TABLE QLKS.CHITIETPHONGDAT (
    MADATPHG INT,
    MAPHG NVARCHAR2(10),
    PRIMARY KEY (MADATPHG, MAPHG)
);

CREATE TABLE QLKS.DICHVU (
    MADV NVARCHAR2(10),
    TENDV NVARCHAR2(100),
    GIA INT,
    PRIMARY KEY (MADV)
);

CREATE TABLE QLKS.CHITIETDATDV (
    MAPHONG NVARCHAR2(10),
    MADV NVARCHAR2(10),
    SOLUONG INT,
    PRIMARY KEY (MAPHONG, MADV)
);

CREATE TABLE QLKS.HOADON (
    MAHD INT,
    MANV INT,
    MADATPHG INT,
    NGAYLAP DATE,
    TONGTIEN INT,
    PRIMARY KEY (MAHD)
);

CREATE TABLE QLKS.TOURDULICH (
    MATOUR NVARCHAR2(10),
    TENTOUR NVARCHAR2(100),
    DIADIEM NVARCHAR2(200),
    GIA INT,
    THOIGIAN DATE,
    PRIMARY KEY (MATOUR)
);

CREATE TABLE QLKS.DKTOUR (
    MADKTOUR INT,
    MATOUR NVARCHAR2(10),
    MAKH INT,
    SONGUOITG INT,
    HINHTHUCDICHUYEN NVARCHAR2(20),
    THOIGIANXUATPHAT DATE,
    NHUCAUDACBIET NVARCHAR2(100),
    PRIMARY KEY (MADKTOUR)
);

CREATE TABLE QLKS.DOITAC (
    MADT NVARCHAR2(10),
    TENDT NVARCHAR2(20),
    MATOUR NVARCHAR2(10),
    DIACHI NVARCHAR2(200),
    SDT NUMBER,
    EMAIL VARCHAR(50),
    PRIMARY KEY (MADT)
);

CREATE TABLE QLKS.QUYDINH (
    MAQD NVARCHAR2(10),
    NOIDUNG NVARCHAR2(200),
    PRIMARY KEY (MAQD)
);
/
--TABLE NHANVIEN
ALTER TABLE QLKS.HOADON ADD FOREIGN KEY (MANV) REFERENCES QLKS.NHANVIEN (MANV); 
--TABLE KHACHHANG
ALTER TABLE QLKS.DATPHONG ADD FOREIGN KEY (MAKH) REFERENCES QLKS.KHACHHANG (MAKH); 
ALTER TABLE QLKS.DKTOUR ADD FOREIGN KEY (MAKH) REFERENCES QLKS.KHACHHANG (MAKH); 
--TABLE LOAIPHONG
ALTER TABLE QLKS.PHONG ADD FOREIGN KEY (TENLOAIPHONG) REFERENCES QLKS.LOAIPHONG (TENLOAIPHONG);
ALTER TABLE QLKS.DATPHONG ADD FOREIGN KEY (TENLOAIPHONG) REFERENCES QLKS.LOAIPHONG (TENLOAIPHONG);
--TABLE PHONG
ALTER TABLE QLKS.CHITIETPHONGDAT ADD FOREIGN KEY (MAPHG) REFERENCES QLKS.PHONG (MAPHONG);
ALTER TABLE QLKS.CHITIETDATDV ADD FOREIGN KEY (MAPHONG) REFERENCES QLKS.PHONG (MAPHONG); 
--TABLE DATPHONG
ALTER TABLE QLKS.CHITIETPHONGDAT ADD FOREIGN KEY (MADATPHG) REFERENCES QLKS.DATPHONG (MADATPHG);
ALTER TABLE QLKS.HOADON ADD FOREIGN KEY (MADATPHG) REFERENCES QLKS.DATPHONG (MADATPHG); 
--TABLE DICHVU
ALTER TABLE QLKS.CHITIETDATDV ADD FOREIGN KEY (MADV) REFERENCES QLKS.DICHVU (MADV); 
--TABLE TOURDULICH
ALTER TABLE QLKS.DKTOUR ADD FOREIGN KEY (MATOUR) REFERENCES QLKS.TOURDULICH (MATOUR); 
ALTER TABLE QLKS.DOITAC ADD FOREIGN KEY (MATOUR) REFERENCES QLKS.TOURDULICH (MATOUR); 
/
create sequence MANV_SEQ
    start with 1
    increment by 1
    maxvalue 100
    nocycle;

create sequence MAKH_SEQ
    start with 1
    increment by 1
    maxvalue 100
    nocycle;
    
create sequence MADATPHONG_SEQ
    start with 1
    increment by 1
    maxvalue 100
    nocycle;
    
create sequence MAHOADON_SEQ
    start with 1
    increment by 1
    maxvalue 100
    nocycle;
    


create sequence MADKTOUR_SEQ
    start with 1
    increment by 1
    maxvalue 100
    nocycle;
    
INSERT INTO QLKS.NHANVIEN VALUES(MANV_SEQ.NEXTVAL,N'Nguyen Thi Dung', N'Hung Vuong, Q1', '0788123000', N'Le tan');

SELECT*FROM QLKS.NHANVIEN;
