exec QLKS.DatPhongKH('Nguyen Thi A','0245689741','Quan 7','Nguyenthia@gmail.com','145','Phong 4 nguoi','P010',TO_DATE('2023-08-15','YYYY-MM-DD'),2);
drop procedure QLKS.DatPhongKH;
CREATE OR REPLACE PROCEDURE QLKS.DatPhongKH(
    TENKH IN NVARCHAR2,
    SDT IN VARCHAR,
    DIACHI IN NVARCHAR2,
    EMAIL IN VARCHAR,
    SOFAX IN VARCHAR,
    TENLOAIPHONG IN NVARCHAR2,
    MAPHG IN VARCHAR,
    NGAYDEN IN DATE,
    SODEMLUUTRU IN INT
)
AS
    makh VARCHAR(10);
    madp VARCHAR(10);
BEGIN
    INSERT INTO QLKS.KHACHHANG VALUES ('', TENKH, SDT, DIACHI, EMAIL, SOFAX,null,null);
    
    select KH.MAKH INTO makh from QLKS.KHACHHANG KH ORDER BY KH.MAKH DESC FETCH FIRST 1 ROWS ONLY; 
        
    INSERT INTO QLKS.DATPHONG VALUES ('', makh, TENLOAIPHONG, NGAYDEN, SODEMLUUTRU);
    
    select DP.MADATPHG INTO madp from QLKS.DATPHONG DP ORDER BY DP.MADATPHG DESC FETCH FIRST 1 ROWS ONLY; 
    
    INSERT INTO QLKS.CHITIETPHONGDAT VALUES (madp, MAPHG);
    
    UPDATE QLKS.PHONG P SET TINHTRANG = 1, TTDONDEP = 'Da don' WHERE  P.MAPHONG=MAPHG;
END;
/

CREATE OR REPLACE PROCEDURE QLKS.DatPhongDoanKH(
    TENKH IN NVARCHAR2,
    SDT IN VARCHAR,
    DIACHI IN NVARCHAR2,
    EMAIL IN VARCHAR,
    SOFAX IN VARCHAR,
    TENDOAN IN NVARCHAR2,
    SOLUONGNGUOI IN INT,
    TENLOAIPHONG IN NVARCHAR2,
    MAPHG IN VARCHAR,
    NGAYDEN IN DATE,
    SODEMLUUTRU IN INT
)
AS
    makh VARCHAR(10);
    madp VARCHAR(10);
BEGIN
    INSERT INTO QLKS.KHACHHANG VALUES ('', TENKH, SDT, DIACHI, EMAIL, SOFAX,TENDOAN,SOLUONGNGUOI);
    
    select KH.MAKH INTO makh from QLKS.KHACHHANG KH ORDER BY KH.MAKH DESC FETCH FIRST 1 ROWS ONLY; 
        
    INSERT INTO QLKS.DATPHONG VALUES ('', makh, TENLOAIPHONG, NGAYDEN, SODEMLUUTRU);
    
    select DP.MADATPHG INTO madp from QLKS.DATPHONG DP ORDER BY DP.MADATPHG DESC FETCH FIRST 1 ROWS ONLY; 
    
    INSERT INTO QLKS.CHITIETPHONGDAT VALUES (madp, MAPHG);
    UPDATE QLKS.PHONG P SET TINHTRANG = 1, TTDONDEP = 'Da don' WHERE P.MAPHONG = MAPHG;
END;
/

CREATE OR REPLACE PROCEDURE QLKS.PhanPhong(
    maDatPhong IN VARCHAR,
    maPhng IN VARCHAR
)
AS 
    maDP VARCHAR(10);
    maphg VARCHAR(10);
    tinhtrang int;
BEGIN
    SELECT MADATPHG INTO maDP FROM QLKS.DATPHONG WHERE MADATPHG=maDatPhong AND ROWNUM = 1;
    SELECT MAPHONG INTO maphg FROM QLKS.PHONG WHERE MAPHONG=maPhng AND ROWNUM = 1;
    SELECT TINHTRANG INTO tinhtrang FROM QLKS.PHONG WHERE MAPHONG=maPhng AND ROWNUM = 1;
    IF(maDatPhong=maDP AND maPhng=maphg AND tinhtrang=0) THEN
        INSERT INTO QLKS.CHITIETPHONGDAT VALUES(maDatPhong,maPhng);
        UPDATE QLKS.PHONG P SET TINHTRANG=1, TTDONDEP='Da don' WHERE P.MAPHONG=maPhng;
    ELSE
        RAISE_APPLICATION_ERROR(-20001,'Phan phong that bai');
    END IF;
END;

exec QLKS.PhanPhong('DP004','P003');
exec QLKS.PhanPhong('DP005','P004');

DELETE FROM QLKS.CHITIETPHONGDAT WHERE MADATPHG = 'DP005';
UPDATE QLKS.PHONG P SET TINHTRANG=0, TTDONDEP='Chua don' WHERE P.MAPHONG='P004';

SELECT * FROM QLKS.PHONG WHERE TINHTRANG = '0';
SELECT * FROM QLKS.PHONG;
SELECT * FROM QLKS.KHACHHANG;
SELECT * FROM QLKS.CHITIETPHONGDAT;
SELECT * FROM QLKS.DATPHONG;